# Generated by Django 4.2.2 on 2023-06-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvester", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_running", models.BooleanField(default=False)),
            ],
        ),
    ]
